name: rotorsync
description: "A new Flutter project."

publish_to: "none"

version: 2.3.1+43

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  lucide_icons: ^0.257.0
  cloud_firestore: ^5.6.5
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  uuid: ^4.5.1
  mqtt_client: ^10.5.1
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.4.0
  flutter_local_notifications: ^19.0.0
  firebase_messaging: ^15.2.4
  flutter_background_service: ^5.1.0
  file_picker: ^10.0.0
  csv: ^6.0.0
  device_info_plus: ^11.3.0
  location: ^7.0.1
  hugeicons: ^0.0.10
  provider: ^6.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
